services:
  - type: web
    name: aladdin-restaurant
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist/public
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
